(load-file "~/.emacs.d/super-emacs/core.el")
(super-emacs/load-config-file "config-system")
(super-emacs/load-config-file "config-repositories")
(super-emacs/load-config-file "config-packages")
(super-emacs/load-config-file "config-interface")
(super-emacs/load-config-file "config-misc")
(super-emacs/load-config-file "config-key-bindings")
(super-emacs/print-startup-message)
