(load-file "~/.emacs.d/super-emacs/core.el")
(se/load-file "config-system")
(se/load-file "config-repositories")
(se/load-file "config-packages")
(se/load-file "config-interface")
(se/load-file "config-misc")
(se/load-file "config-key-bindings")
(se/print-startup-message)
